apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::416472087231:role/eksctl-roboshop-nodegroup-expense-NodeInstanceRole-whsw7Rttme5n
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::416472087231:user/shiva
      username: shiva
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-25T09:51:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1389"
  uid: e653f2cf-7e06-4bcb-8979-c26c45df3011
